version: '2'

services:
  baikal:
    build: docker-baikal
    volumes:
      - ./baikaldata:/baikal/Specific
    expose:
      - "80"
    restart: always
  bamboo-redirect:
    image: geldim/https-redirect
    ports:
      - "80:80"
  ssl-proxy:
    image: fsouza/docker-ssl-proxy
    environment:
      DOMAIN: nfoonf.org 
      TARGET_PORT: 80
      TARGET_HOST: baikal
      CLIENT_MAX_BODY_SIZE:
    # put valid certs and keys here
    volumes:
      - ./certdata:/etc/nginx/certs
    ports:
      - "8080:443"
      - "443:443"


